version: "3.8"

services:
  php:
    image: php:7.3.33-fpm
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - dev_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dev_network

  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Supp0rt
      MYSQL_USER: support
      MYSQL_PASSWORD: Supp0rt
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  db_data:
